sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'

services:
  - rabbitmq

addons:
  code_climate:
    repo_token: 0bc730d2a5a3920e5d27e0839e44ca3ca333bbf87c3a5cbf4ab6c19d13836098

after_script:
  - codeclimate < ./coverage/lcov.info
